/// Marker trait for types that can be bound as SQL parameters.
///
/// Generated by `#[derive(PatchQuery)]` in `jolt-macros`. The proc-macro
/// emits `&self` fields as `&dyn ToSql` references inside the generated
/// `fn to_patch_query(…)` parameter Vec.
///
/// Blanket impls for common scalar types keep user structs ergonomic — no
/// manual impls needed for `u32`, `String`, `&str`, `bool`, etc.
///
/// `ToSql` is deliberately NOT sealed: downstream crates can implement it for
/// their own domain types (e.g. a wrapper around UUID or a custom enum) and
/// pass them directly to patch queries.
pub trait ToSql {}

impl ToSql for u8 {}
impl ToSql for u16 {}
impl ToSql for u32 {}
impl ToSql for u64 {}
impl ToSql for i8 {}
impl ToSql for i16 {}
impl ToSql for i32 {}
impl ToSql for i64 {}
impl ToSql for f32 {}
impl ToSql for f64 {}
impl ToSql for bool {}
impl ToSql for String {}
impl ToSql for &str {}
impl<T: ToSql> ToSql for &T {}
