const std = @import("std");

pub const MimeTypes = std.StaticStringMap([]const u8).initComptime(.{
    .{ "audio/aac", "" },
    .{ "audio/mpeg", "" },
    .{ "audio/ogg", "" },
    .{ "audio/wav", "" },
    .{ "audio/webm", "" },
    .{ "image/avif", "" },
    .{ "image/jpeg", &.{ 0xFF, 0xD8 } },
    .{ "image/png", &.{ 0x89, 0x50, 0x4E, 0x47, 0x0D, 0x0A, 0x1A, 0x0A } },
    .{ "image/gif", &.{ 0x47, 0x49, 0x46 } },
    .{ "image/webp", "" },
    .{ "video/mp4", "" },
    .{ "video/mpeg", "" },
    .{ "video/ogg", "" },
    .{ "video/webm", "" },
    .{ "application/pdf", "" },
    .{ "application/msword", "" },
    .{ "application/vnd.openxmlformats-officedocument.wordprocessingml.document", "" },
    .{ "application/vnd.ms-excel", "" },
    .{ "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "" },
    .{ "application/vnd.ms-powerpoint", "" },
    .{ "application/vnd.openxmlformats-officedocument.presentationml.presentation", "" },
    .{ "application/gzip", "" },
    .{ "application/zip", "" },
    .{ "application/x-zip-compressed", "" },
    .{ "application/x-7z-compressed", "" },
});
