name: CI

on:
  pull_request

permissions:
  id-token: write
  contents: read
  checks: read

jobs:
  tests:
    runs-on: ubuntu-latest
    name: Run Tests
    steps:
      - uses: actions/checkout@v4
      - uses: mlugg/setup-zig@v2
        with:
          version: 0.15.1

      - name: Jolt tests
        run: zig build test --summary all

